<?php

namespace FedexApiClass\Lib;

class AssociatedShipmentType
{
    const __default = 'COD_AND_DELIVERY_ON_INVOICE_ACCEPTANCE_RETURN';
    const COD_AND_DELIVERY_ON_INVOICE_ACCEPTANCE_RETURN = 'COD_AND_DELIVERY_ON_INVOICE_ACCEPTANCE_RETURN';
    const COD_RETURN = 'COD_RETURN';
    const DELIVERY_ON_INVOICE_ACCEPTANCE_RETURN = 'DELIVERY_ON_INVOICE_ACCEPTANCE_RETURN';


}
