<?php

namespace FedexApi\Lib;

class ClearanceBrokerageType
{
    const __default = 'BROKER_INCLUSIVE';
    const BROKER_INCLUSIVE = 'BROKER_INCLUSIVE';
    const BROKER_INCLUSIVE_NON_RESIDENT_IMPORTER = 'BROKER_INCLUSIVE_NON_RESIDENT_IMPORTER';
    const BROKER_SELECT = 'BROKER_SELECT';
    const BROKER_SELECT_NON_RESIDENT_IMPORTER = 'BROKER_SELECT_NON_RESIDENT_IMPORTER';
    const BROKER_UNASSIGNED = 'BROKER_UNASSIGNED';


}
