<?php

namespace FedexApi\Lib;

class CustomerSpecifiedLabelGenerationOptionType
{
    const __default = 'CONTENT_ON_SHIPPING_LABEL_ONLY';
    const CONTENT_ON_SHIPPING_LABEL_ONLY = 'CONTENT_ON_SHIPPING_LABEL_ONLY';
    const CONTENT_ON_SHIPPING_LABEL_PREFERRED = 'CONTENT_ON_SHIPPING_LABEL_PREFERRED';
    const CONTENT_ON_SUPPLEMENTAL_LABEL_ONLY = 'CONTENT_ON_SUPPLEMENTAL_LABEL_ONLY';


}
