<?php

namespace FedexApi\Lib;

class FedExLocationType
{
    const __default = 'FEDEX_EXPRESS_STATION';
    const FEDEX_EXPRESS_STATION = 'FEDEX_EXPRESS_STATION';
    const FEDEX_FACILITY = 'FEDEX_FACILITY';
    const FEDEX_FREIGHT_SERVICE_CENTER = 'FEDEX_FREIGHT_SERVICE_CENTER';
    const FEDEX_GROUND_TERMINAL = 'FEDEX_GROUND_TERMINAL';
    const FEDEX_HOME_DELIVERY_STATION = 'FEDEX_HOME_DELIVERY_STATION';
    const FEDEX_OFFICE = 'FEDEX_OFFICE';
    const FEDEX_SHIPSITE = 'FEDEX_SHIPSITE';
    const FEDEX_SMART_POST_HUB = 'FEDEX_SMART_POST_HUB';


}
