<?php

namespace FedexApiClass\Lib;

class HazardousCommodityOptionType
{
    const __default = 'BATTERY';
    const BATTERY = 'BATTERY';
    const HAZARDOUS_MATERIALS = 'HAZARDOUS_MATERIALS';
    const LIMITED_QUANTITIES_COMMODITIES = 'LIMITED_QUANTITIES_COMMODITIES';
    const ORM_D = 'ORM_D';
    const REPORTABLE_QUANTITIES = 'REPORTABLE_QUANTITIES';
    const SMALL_QUANTITY_EXCEPTION = 'SMALL_QUANTITY_EXCEPTION';


}
