<?php

namespace FedexApiClass\Lib;

class LabelStockType
{
    const __default = 'PAPER_4X6';
    const PAPER_4X6 = 'PAPER_4X6';
    const PAPER_4X8 = 'PAPER_4X8';
    const PAPER_4X9 = 'PAPER_4X9';
    const PAPER_6X4 = 'PAPER_6X4';
    const PAPER_7X475 = 'PAPER_7X4.75';
    const PAPER_85X11_BOTTOM_HALF_LABEL = 'PAPER_8.5X11_BOTTOM_HALF_LABEL';
    const PAPER_85X11_TOP_HALF_LABEL = 'PAPER_8.5X11_TOP_HALF_LABEL';
    const PAPER_LETTER = 'PAPER_LETTER';
    const STOCK_4X6 = 'STOCK_4X6';
    const STOCK_4X675_LEADING_DOC_TAB = 'STOCK_4X6.75_LEADING_DOC_TAB';
    const STOCK_4X675_TRAILING_DOC_TAB = 'STOCK_4X6.75_TRAILING_DOC_TAB';
    const STOCK_4X8 = 'STOCK_4X8';
    const STOCK_4X9_LEADING_DOC_TAB = 'STOCK_4X9_LEADING_DOC_TAB';
    const STOCK_4X9_TRAILING_DOC_TAB = 'STOCK_4X9_TRAILING_DOC_TAB';


}
