<?php

namespace FedexApi\Lib;

class LabelMaskableDataType
{
    const __default = 'CUSTOMS_VALUE';
    const CUSTOMS_VALUE = 'CUSTOMS_VALUE';
    const DUTIES_AND_TAXES_PAYOR_ACCOUNT_NUMBER = 'DUTIES_AND_TAXES_PAYOR_ACCOUNT_NUMBER';
    const SHIPPER_ACCOUNT_NUMBER = 'SHIPPER_ACCOUNT_NUMBER';
    const TERMS_AND_CONDITIONS = 'TERMS_AND_CONDITIONS';
    const TRANSPORTATION_CHARGES_PAYOR_ACCOUNT_NUMBER = 'TRANSPORTATION_CHARGES_PAYOR_ACCOUNT_NUMBER';


}
