<?php

namespace FedexApiClass\Lib;

class RequestedShippingDocumentType
{
    const __default = 'CERTIFICATE_OF_ORIGIN';
    const CERTIFICATE_OF_ORIGIN = 'CERTIFICATE_OF_ORIGIN';
    const COMMERCIAL_INVOICE = 'COMMERCIAL_INVOICE';
    const CUSTOMER_SPECIFIED_LABELS = 'CUSTOMER_SPECIFIED_LABELS';
    const CUSTOM_PACKAGE_DOCUMENT = 'CUSTOM_PACKAGE_DOCUMENT';
    const CUSTOM_SHIPMENT_DOCUMENT = 'CUSTOM_SHIPMENT_DOCUMENT';
    const DANGEROUS_GOODS_SHIPPERS_DECLARATION = 'DANGEROUS_GOODS_SHIPPERS_DECLARATION';
    const EXPORT_DECLARATION = 'EXPORT_DECLARATION';
    const FREIGHT_ADDRESS_LABEL = 'FREIGHT_ADDRESS_LABEL';
    const GENERAL_AGENCY_AGREEMENT = 'GENERAL_AGENCY_AGREEMENT';
    const LABEL = 'LABEL';
    const NAFTA_CERTIFICATE_OF_ORIGIN = 'NAFTA_CERTIFICATE_OF_ORIGIN';
    const OP_900 = 'OP_900';
    const PRO_FORMA_INVOICE = 'PRO_FORMA_INVOICE';
    const RETURN_INSTRUCTIONS = 'RETURN_INSTRUCTIONS';


}
