<?php

namespace FedexApi\Lib;

class ReturnedShippingDocumentType
{
    const __default = 'AUXILIARY_LABEL';
    const AUXILIARY_LABEL = 'AUXILIARY_LABEL';
    const CERTIFICATE_OF_ORIGIN = 'CERTIFICATE_OF_ORIGIN';
    const COD_AND_DELIVERY_ON_INVOICE_ACCEPTANCE_RETURN_2_D_BARCODE = 'COD_AND_DELIVERY_ON_INVOICE_ACCEPTANCE_RETURN_2_D_BARCODE';
    const COD_AND_DELIVERY_ON_INVOICE_ACCEPTANCE_RETURN_LABEL = 'COD_AND_DELIVERY_ON_INVOICE_ACCEPTANCE_RETURN_LABEL';
    const COD_RETURN_2_D_BARCODE = 'COD_RETURN_2_D_BARCODE';
    const COD_RETURN_LABEL = 'COD_RETURN_LABEL';
    const COMMERCIAL_INVOICE = 'COMMERCIAL_INVOICE';
    const CUSTOM_PACKAGE_DOCUMENT = 'CUSTOM_PACKAGE_DOCUMENT';
    const CUSTOM_SHIPMENT_DOCUMENT = 'CUSTOM_SHIPMENT_DOCUMENT';
    const DANGEROUS_GOODS_SHIPPERS_DECLARATION = 'DANGEROUS_GOODS_SHIPPERS_DECLARATION';
    const DELIVERY_ON_INVOICE_ACCEPTANCE_RETURN_2_D_BARCODE = 'DELIVERY_ON_INVOICE_ACCEPTANCE_RETURN_2_D_BARCODE';
    const DELIVERY_ON_INVOICE_ACCEPTANCE_RETURN_LABEL = 'DELIVERY_ON_INVOICE_ACCEPTANCE_RETURN_LABEL';
    const ETD_LABEL = 'ETD_LABEL';
    const EXPORT_DECLARATION = 'EXPORT_DECLARATION';
    const FREIGHT_ADDRESS_LABEL = 'FREIGHT_ADDRESS_LABEL';
    const GENERAL_AGENCY_AGREEMENT = 'GENERAL_AGENCY_AGREEMENT';
    const GROUND_BARCODE = 'GROUND_BARCODE';
    const NAFTA_CERTIFICATE_OF_ORIGIN = 'NAFTA_CERTIFICATE_OF_ORIGIN';
    const OP_900 = 'OP_900';
    const OUTBOUND_2_D_BARCODE = 'OUTBOUND_2_D_BARCODE';
    const OUTBOUND_LABEL = 'OUTBOUND_LABEL';
    const PRO_FORMA_INVOICE = 'PRO_FORMA_INVOICE';
    const RECIPIENT_ADDRESS_BARCODE = 'RECIPIENT_ADDRESS_BARCODE';
    const RECIPIENT_POSTAL_BARCODE = 'RECIPIENT_POSTAL_BARCODE';
    const RETURN_INSTRUCTIONS = 'RETURN_INSTRUCTIONS';
    const TERMS_AND_CONDITIONS = 'TERMS_AND_CONDITIONS';
    const USPS_BARCODE = 'USPS_BARCODE';


}
