<?php

namespace FedexApiClass\Lib;

class ReturnedRateType
{
    const __default = 'INCENTIVE';
    const INCENTIVE = 'INCENTIVE';
    const PAYOR_ACCOUNT_PACKAGE = 'PAYOR_ACCOUNT_PACKAGE';
    const PAYOR_ACCOUNT_SHIPMENT = 'PAYOR_ACCOUNT_SHIPMENT';
    const PAYOR_LIST_PACKAGE = 'PAYOR_LIST_PACKAGE';
    const PAYOR_LIST_SHIPMENT = 'PAYOR_LIST_SHIPMENT';
    const PREFERRED_ACCOUNT_PACKAGE = 'PREFERRED_ACCOUNT_PACKAGE';
    const PREFERRED_ACCOUNT_SHIPMENT = 'PREFERRED_ACCOUNT_SHIPMENT';
    const PREFERRED_LIST_PACKAGE = 'PREFERRED_LIST_PACKAGE';
    const PREFERRED_LIST_SHIPMENT = 'PREFERRED_LIST_SHIPMENT';


}
